[package]
name = "rustrt_native"
version = "1.0.0"
authors = ["The Rust Project Developers"]
links = "rustrt_native"
build = "build.rs"

[lib]
name = "rustrt_native"
path = "lib.rs"

[build-dependencies]
gcc = "0.3"
