[package]
name = "morestack"
version = "1.0.0"
authors = ["The Rust Project Developers"]
links = "morestack"
build = "build.rs"

[lib]
name = "morestack"
path = "lib.rs"

[build-dependencies]
gcc = "0.3"
